### ISSUE TITLE
dotnet tests are not supported

### ISSUE THREAD

**Issue by yrandin** [chrisjwalk/angular-cli-netcore-ngrx-starter#14]
Hello,

Looks like dotnet tests are not supported by the dotnet-builder.

I could share my implementation for tests, should I create a pull request ?

Best Regards,
Yann

**Comment by chrisjwalk** [comment]
Hi Yann!

Yes, please, all PRs are welcome.

Thanks,

-Chris

**Comment by chrisjwalk** [comment]
Thanks for the PR!
